WarlordsGameBundle_homepage:
    pattern:  /
    defaults: { _controller: WarlordsGameBundle:Main:index }
    requirements:
        _method:  GET
        
        
WarlordsGameBundle_player:
    pattern: /player
    defaults: { _controller: WarlordsGameBundle:Page:player }
    requirements:
        _method: GET

login:
    pattern:   /login
    defaults:  { _controller: WarlordsGameBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern: /logout

WarlordsGameBundle_profile_get:
    pattern: /profile/{target_id}
    defaults:  { _controller: WarlordsGameBundle:Profile:profile_get }
    requirements:
        _method:  GET
        id: \d+

WarlordsGameBundle_profile:
    pattern: /profile
    defaults:  { _controller: WarlordsGameBundle:Profile:profile }
    requirements:
        _method:  GET
                
WarlordsGameBundle_attack:
    pattern: /attack/{target_id}
    defaults:  { _controller: WarlordsGameBundle:Profile:attack }
    requirements:
        _method:  GET
        
WarlordsGameBundle_buy_soldier:
    pattern: /profile/buy
    defaults:  { _controller: WarlordsGameBundle:Profile:buy }
    requirements:
        _method:  GET | POST
        id: \d+
