WarlordsGameBundle_homepage:
    pattern:  /
    defaults: { _controller: WarlordsGameBundle:Main:index }
    requirements:
        _method:  GET
        
        
WarlordsGameBundle_player:
    pattern: /player
    defaults: { _controller: WarlordsGameBundle:Page:player }
    requirements:
        _method: GET
