WarlordsGameBundle_homepage:
    pattern:  /
    defaults: { _controller: WarlordsGameBundle:Main:index }
    requirements:
        _method:  GET

login:
    pattern:   /login
    defaults:  { _controller: WarlordsGameBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern: /logout


WarlordsGameBundle_profile:
    pattern: /profile
    defaults:  { _controller: WarlordsGameBundle:Profile:profile }
    requirements:
        _method:  GET
        id: \d+
