parameters:
#    warlords_game.example.class: Warlords\GameBundle\Example

services:
#    warlords_game.example:
#        class: %warlords_game.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    warlords_user.form.handler.registration:
        class: Warlords\GameBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false

    warlords_user.registration.form.type:
        class: Warlords\GameBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: warlords_user_registration }

    warlords_user.form.handler.resetting:
        class: Warlords\GameBundle\Form\Handler\ResettingFormHandler
        arguments: ["@fos_user.resetting.form", "@request", "@fos_user.user_manager"]
        scope: request
        public: false

    warlords_user.resetting.form.type:
        class: Warlords\GameBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: warlords_reset_password }

    warlords_user.form.handler.change_password:
        class: Warlords\GameBundle\Form\Handler\ChangePasswordFormHandler
        arguments: ["@fos_user.change_password.form", "@request", "@fos_user.user_manager"]
        scope: request

    warlords_user.changepassword.form.type:
        class: Warlords\GameBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: warlords_change_password }
            
    activity_listener:
        class: Warlords\GameBundle\Listener\Activity
        arguments: [@security.context, @doctrine]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
