FOS\UserBundle\Model\User:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [username, usernameCanonical], groups: [Register], message: The username is already used. }
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [email, emailCanonical], groups: [Register], message: The email is already used. }
    properties:
        username: 
            - NotBlank: 
                groups: [Register]
                message: You must enter a username.
            - MinLength: 
                groups: [Register]
                limit: 6
                message: Username must be at least 6 characters long.
            - MaxLength: 
                groups: [Register] 
                limit: 50
                message: Username cannot be longer than 50 characters.
            - Regex:
                groups: [Register]
                pattern: /^[a-zA-Z0-9 _]*$/
                match: true
                message: Username can only contain letters, digits or underscore "_".
            - Regex:
                groups: [Register]
                pattern: /^[a-zA-Z]/
                match: true
                message: Username must start with a letter.
            - Regex:
                groups: [Register]
                pattern: /[a-zA-Z0-9]$/
                match: true
                message: Username must end with a letter or number.
         #   - Callback: http://symfony.com/doc/current/reference/constraints/Callback.html
         #       methods:   [isUserValid]
        email:
            - NotBlank:
                groups: [Register]
                message: You must enter an email address.
            - Email: 
                groups: [Register]
                message: The email address "{{ value }}" is not a valid email address.
                checkMX: true
            - MinLength: 
                groups: [Register] 
                limit: 6
                message: Email address cannot be shorter than 6 characters.
            - MaxLength: 
                groups: [Register] 
                limit: 100
                message: Email address cannot be longer than 100 characters.
        plainPassword:
            - NotBlank:
                groups: [Register]
                message: You must enter a password.
            - MinLength:
                groups: [Register]
                limit: 6
                message: Password must be 6-14 characters long.
            - MaxLength: 
                groups: [Register] 
                limit: 14
                message: Password must be 6-14 characters long.
Warlords\GameBundle\Entity\PlayerStats:
        properties:
            infantry:
                - Type: \Integer
