imports:
    - { resource: parameters.yml }  # contains sensitive configuration; should not upload to git
    - { resource: globals.yml }     # contains global configuration used by warlords
    - { resource: security.yml }    # contains security parameters
    - { resource: @WarlordsGameBundle/Resources/config/services.yml }


framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Warlords\GameBundle\Entity\User
    registration:
        form:
            handler: warlords_user.form.handler.registration
            type: warlords_user_registration
            validation_groups: [Register]
        confirmation:
            enabled: true
    resetting:
        form:
            handler:            warlords_user.form.handler.resetting
            type:               warlords_reset_password
            validation_groups:  [Resetting]
        email:
            from_email:
                address:        resetting@noreply.com
                sender_name:    WARLORDS NOREPLY
        token_ttl: 604800    #persist for only a week
        email:
            template: FOSUserBundle:Resetting:email.txt.twig
    change_password:
        form:
            type:               warlords_change_password
            handler:            warlords_user.form.handler.change_password
    from_email:
        address:        group10weweb@gmail.com
        sender_name:    WARLORDS ADMIN
    service:
        mailer: fos_user.mailer.twig_swift
        
services:
    authentication_handler:
        class: Warlords\GameBundle\Handler\AuthenticationHandler
    warlords.twig.warlords_extension:
        class: Warlords\GameBundle\Twig\WarlordsExtension
        tags:
            - { name: twig.extension }
   
fos_message:
    db_driver: orm
    thread_class:           Warlords\GameBundle\Entity\Thread
    message_class:          Warlords\GameBundle\Entity\Message

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals: 
        warlords_admin_email: group10weweb@gmail.com
        warlords_wealthboard_top: %warlords.wealthboard.top%
        warlords_fameboard_top: %warlords.fameboard.top%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Captcha
genemu_form:
    captcha:
        width:            120
        height:           40
        length:           6
        format:           png
        chars:            0123456789
        font_size:        18
        font_color:       ['252525', '8B8787', '550707', '3526E6', '88531E']
        font_dir:         %kernel.root_dir%/../web/bundles/genemuform/fonts
        fonts:            ['akbar.ttf', 'brushcut.ttf', 'molten.ttf', 'planetbe.ttf', 'whoobub.ttf']
        background_color: DDDDDD
        border_color:     000000

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
