parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: warlords
    database_user: root
    database_password: weweb
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: fdcab712e14e7b80dd7e3693b986b3410d268f04
    database_path: null

