jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Warlords\GameBundle\Entity\User:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: Warlords\GameBundle\Entity\User, property: username}

    firewalls:
#        main:
#            form_login:
#                username_parameter: 'login[username]'
#                password_parameter: 'login[password]'
#                csrf_parameter:     'login[_token]'
#                csrf_provider:      form.csrf_provider
#
#                use_referer:  true
#                default_target_path: /profile
#            remember_me:
#                key:      secret
#                lifetime: 10 
#                path:     /profile
#                domain:   ~ # Defaults to the current domain from $_SERVER
#                remember_me_parameter: 'login[remember_me]'

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:  ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /profile
            logout: ~
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/profile , roles: ROLE_USER}
