jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                default_target_path: /
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_forward:    false
                check_path:     /login_check
                use_referer: true
                success_handler: authentication_handler
                failure_handler: authentication_handler 
                login_path: /login
                default_target_path: /profile 
            logout:       
                path:   /logout
                target: /
                success_handler: authentication_handler
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 86400 # 1 day in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
#                remember_me_parameter: 'login[remember_me]'

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:  ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /profile
            logout: ~
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile , roles: ROLE_USER}
        - { path: ^/attack , roles: ROLE_USER}
        - { path: ^/player , roles: ROLE_USER }
        - { path: ^/change-password , roles: ROLE_USER }
