Warlords\GameBundle\Entity\Ally:
    type: entity
    table: ally
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        ally:
            type: string
            length: 255
        isActive:
            type: boolean
        isBlocked:
            type: boolean
    manyToOne:
        user:    
            targetEntity: User
    
    lifecycleCallbacks: {  }
