Warlords\GameBundle\Entity\Guild:
    type: entity
    table: guilds
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        name:
            type: string
            length: 255
    oneToOne:
        leader:
            targetEntity: User
            inversedBy: user
            type: integer
            nullable: false
