Warlords\GameBundle\Entity\PlayerStats:
    type: entity
    table: playerStats
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        level:
            type: integer
        exp:
            type: integer
        sp:
            type: integer
        fame:
            type: integer
        land:
            type: integer
        gold:
            type: integer
        infantry:
            type: integer
        knights:
            type: integer
        calvary:
            type: integer
    oneToOne:
        user:
            targetEntity: User
            inversedBy: stats
    oneToMany:
        skills:
            targetEntity: Skills
            mappedBy: stats
    lifecycleCallbacks: {  }
