Warlords\GameBundle\Entity\SecurityQuestions:
    type: entity
    table: securityQuestions
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
            
    fields:
        answer:
            type: string
            length: 255
        question:
            type: string
            length: 255
    oneToOne:
        user_id:
            targetEntity: User
