Warlords\GameBundle\Entity\Skill:
    type: entity
    table: skill
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        level:
            type: integer
        isActive:
            type: boolean
        start_time:
            type: datetime
    oneToOne:
        skill:
            targetEntity: SkillList
    manyToOne:
        stats:
            targetEntity: Stats
            inversedBy: skills
    lifecycleCallbacks: {  }
