Warlords\GameBundle\Entity\Skills:
    type: entity
    table: skills
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
    fields:
        #level of this skill
        level:
            type: integer
            nullable: true
        #instances casted, spells should only be casted 3 times per hour.
        instances:
            type: integer
            nullable: false
        #for attack and defense increase spells. Should turn inactive after 3 instances
        isActive:
            type: boolean
        #for tracking how long since it is active.
        casted_time:
            type: datetime
    oneToOne:
        skill:
            targetEntity: SkillList
    manyToOne:
        stats:
            targetEntity: PlayerStats
            inversedBy: skills
    lifecycleCallbacks: {  }
