Warlords\GameBundle\Entity\User:
    type: entity
    table: user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        username:
            type: string
            length: 50
            unique: true
        salt:
            type: string
            length: 255
            nullable: true
        password:
            type: string
            length: 255
        email:
            type: string
            length: 100
            nullable: true
        isActive:
            type: boolean
    oneToOne:
        stats:
            targetEntity: PlayerStats
            mappedBy: user
    manyToMany:
        alliesWithMe:
            targetEntity: User
            mappedBy: myAllies
        myAllies:
            targetEntity: User
            inversedBy: alliesWithMe
            joinTable:
                name: allies
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    ally_user_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
